### ISSUE TITLE
I want to improve the UI of the calculator

### ISSUE THREAD

**Issue by shivi11g** [Thisarahetz/Calculator-Hacktoberfest2022#11]

**Comment by shivi11g** [comment]
I want to improve the UI of this calculator, kindly assign me this issue.

**Comment by Thisarahetz** [comment]
space between buttons

**Comment by avijain09** [comment]
can u please assign this issue to me @Thisarahetz

**Comment by Hiresh23** [comment]
i would like to contribute , please assign
