### ISSUE TITLE
Improve how calculations are being done

### ISSUE THREAD

**Issue by Saavrm26** [Thisarahetz/Calculator-Hacktoberfest2022#31]
Use dedicated algorithm to calculate the string rather than using eval

**Comment by Saavrm26** [comment]
May i be assigned to this issue

**Comment by Thisarahetz** [comment]
Shur. @Saavrm26 you can fix it

**Comment by Saavrm26** [comment]
If this pr gets merged i'll add a documentation detailing how to add new functions to the calculator

**Comment by Saavrm26** [comment]
This feature requires more testing, if there is any error in the calculations, let me know.

**Comment by Saavrm26** [comment]
Should i raise another issue for the documentation?
And should i close this issue
